name: build-and-deploy-steamos-docker-image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  BUILDKIT_PROGRESS: 'plain'
  STEAMOS_VERSION: 3
  DOCKER_IMAGE: 'zerosuxx/steamdeck-steamos'
  RECOVERY_IMAGE: 'steamdeck-recovery-1.img'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download recovery image
        run: wget https://steamdeck-images.steamos.cloud/recovery/${{ env.RECOVERY_IMAGE }}.bz2

      - name: Extract recovery image
        run: bzip2 -d ${{ env.RECOVERY_IMAGE }}.bz2

      - name: Build docker image from recovery image
        run: |
          sudo apt-get install -y libguestfs-tools
          sudo guestfish \
            --ro \
            -a ${{ env.RECOVERY_IMAGE }} \
            -m /dev/sda3:/ \
            -m /dev/sda4:/var \
            -m /dev/sda5:/home \
            tar-out / - | docker import - ${{ env.DOCKER_IMAGE }}:${{ env.STEAMOS_VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy docker image to docker hub
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.STEAMOS_VERSION }} ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.STEAMOS_VERSION }}
          docker push ${{ env.DOCKER_IMAGE }}:latest
