name: build-and-deploy-recovery-docker-image

on:
  workflow_dispatch:

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  BUILDKIT_PROGRESS: 'plain'
  STEAMOS_VERSION: 3
  DOCKER_IMAGE: 'zerosuxx/steamdeck-steamos-recovery'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set recovery image
        run: echo "RECOVERY_IMAGE=$(curl -s https://steamdeck-images.steamos.cloud/recovery/ | grep -oP 'title=\"(.*.bz2)\"' | tail -1 | cut -c8- | rev | cut -c6- | rev)" >> $GITHUB_ENV

      - name: Download recovery image
        run: wget https://steamdeck-images.steamos.cloud/recovery/$RECOVERY_IMAGE.bz2

      - name: Extract recovery image
        run: bzip2 -d $RECOVERY_IMAGE.bz2

      - name: Build docker image from recovery image
        run: |
          sudo apt-get install -y libguestfs-tools
          sudo guestfish \
            --ro \
            -a $RECOVERY_IMAGE \
            -m /dev/sda3:/ \
            -m /dev/sda4:/var \
            -m /dev/sda5:/home \
            tar-out / - | docker import - ${{ env.DOCKER_IMAGE }}:${{ env.STEAMOS_VERSION }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Deploy docker image to docker hub
        run: |
          docker tag ${{ env.DOCKER_IMAGE }}:${{ env.STEAMOS_VERSION }} ${{ env.DOCKER_IMAGE }}:latest
          docker push ${{ env.DOCKER_IMAGE }}:${{ env.STEAMOS_VERSION }}
          docker push ${{ env.DOCKER_IMAGE }}:latest
